#!/usr/bin/env python3

from __future__ import annotations

import os
import json
import argparse
from typing import List, Dict, Any, Tuple
from collections import Counter, defaultdict
import re

from jericho_qa_utils import load_jsonl, JerichoQAUtils, pick_negative_from_pool

from typing import Optional  # needed for type hints in batch paraphrase

def batch_paraphrase_qas(qas: List[Dict[str, Any]], paraphrase: bool = True, ratio: float = 0.5, batch_size: int = 8) -> None:
    """
    Post‑process a list of QA dictionaries to paraphrase a subset of questions in batch.

    This function groups questions by their (template, question) pairs, randomly selects
    a fraction of unique questions per template, and sends them to the OpenAI API in
    batches for paraphrasing.  The paraphrased text replaces the ``paraphrase``
    field in each affected QA entry.  If paraphrasing is disabled or no API key
    is provided, the function exits without modification.

    :param qas: List of QA pairs generated by ``generate_questions``.
    :param paraphrase: Whether to perform paraphrasing (if False, no changes).
    :param ratio: Fraction of unique questions per template to paraphrase (default 0.5).
    :param batch_size: Number of questions to send to the model in one API call.
    """
    if not paraphrase:
        return
    import os
    import json
    import random
    # Import OpenAI client lazily
    try:
        from openai import OpenAI  # type: ignore
    except Exception as e:
        raise RuntimeError("openai package is required. Try: pip install openai") from e
    # Retrieve API key and base URL from environment (use provided defaults if missing)
    api_key = os.environ.get(
        "OPENAI_API_KEY",
        "sk-keKB2Y0DPJFFqWPblW6pWueLFkrq6gk66QkbqgzLc5sAxC46",
    )
    base_url = os.environ.get(
        "OPENAI_BASE_URL",
        "http://35.220.164.252:3888/v1",
    )
    # If API key is not available, skip paraphrasing
    if not api_key:
        return
    client = OpenAI(api_key=api_key, base_url=base_url)
    # Build mapping from (template, question) to indices
    from collections import defaultdict
    key_to_indices: Dict[Tuple[str, str], List[int]] = defaultdict(list)
    for idx, qa in enumerate(qas):
        tmpl = qa.get("template", "")
        question = qa.get("question", "")
        key_to_indices[(tmpl, question)].append(idx)
    # Group unique keys by template
    tmpl_to_keys: Dict[str, List[Tuple[str, str]]] = defaultdict(list)
    for key in key_to_indices:
        tmpl_to_keys[key[0]].append(key)
    # Choose keys to paraphrase
    keys_to_paraphrase: List[Tuple[str, str]] = []
    random.seed(0)
    for tmpl, keys in tmpl_to_keys.items():
        random.shuffle(keys)
        total = len(keys)
        # Determine number to paraphrase; at least one if any keys exist
        k = int(total * ratio)
        if k <= 0 and total > 0:
            k = 1
        # Extend list with selected keys
        keys_to_paraphrase.extend(keys[:k])
    # Perform paraphrasing in batches
    for i in range(0, len(keys_to_paraphrase), batch_size):
        batch_keys = keys_to_paraphrase[i : i + batch_size]
        if not batch_keys:
            continue
        batch_questions = [key[1] for key in batch_keys]
        # Compose messages for the API
        messages = [
            {
                "role": "system",
                "content": (
                    "You are a helpful assistant that paraphrases questions without changing their meaning. "
                    "Do not alter or replace any game-specific entities such as items, actions, or locations. "
                    "You will receive a JSON list of question strings. "
                    "Return a JSON list of paraphrased question strings of the same length and order."
                ),
            },
            {
                "role": "user",
                "content": json.dumps(batch_questions, ensure_ascii=False),
            },
        ]
        try:
            response = client.chat.completions.create(
                model="gpt-4o",
                messages=messages,
                temperature=0.0,
            )
            content = response.choices[0].message.content
            paraphrased_list = json.loads(content) if content else batch_questions
        except Exception:
            paraphrased_list = batch_questions
        # Assign paraphrased text to all corresponding QA entries
        for key, new_question in zip(batch_keys, paraphrased_list):
            indices = key_to_indices.get(key, [])
            for idx in indices:
                # Replace the paraphrase field; if new_question is empty, keep original
                if new_question:
                    qas[idx]["paraphrase"] = new_question


def write_json(path: str, obj: Any) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(obj, f, ensure_ascii=False, indent=2)


def write_jsonl(path: str, rows: List[Dict[str, Any]]) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        for row in rows:
            f.write(json.dumps(row, ensure_ascii=False) + "\n")


def generate_questions(qa_utils: JerichoQAUtils, difficulty: int = -1, max_per_type: int = 5, paraphrase: bool = True) -> List[Dict[str, Any]]:
    """Generate a diverse set of question–answer pairs for a Jericho trajectory.
    """
    import random
    qas: List[Dict[str, Any]] = []
    # Determine how many steps to consider.  If a positive difficulty value is
    # supplied, it truncates the trajectory so that only the first
    # ``difficulty`` steps are used for both generating questions and computing
    # answers.  Otherwise, the full length of the log is used.
    orig_n = qa_utils.n
    if difficulty is not None and difficulty > 0:
        n = min(orig_n, difficulty)
    else:
        n = orig_n
    if n <= 0:
        return qas
    # Seed for reproducibility
    random.seed(0)
    # Build an adjacency filtered by the truncation point.  When truncating,
    # include only those transitions whose first discovery occurred within
    # the first ``n`` steps.  Otherwise use the full adjacency from qa_utils.
    from collections import defaultdict, deque
    adjacency_filtered = qa_utils.adj
    if difficulty is not None and difficulty > 0:
        threshold_step_num = None
        if (n - 1) < len(qa_utils.steps):
            try:
                threshold_step_num = int(qa_utils.steps[n - 1])
            except Exception:
                threshold_step_num = None
        tmp_adj: Dict[str, List[Tuple[str, str]]] = defaultdict(list)
        edges = []
        try:
            edges = qa_utils.dynamic_map.get("edges", [])
        except Exception:
            edges = []
        if threshold_step_num is not None and edges:
            for edge in edges:
                fs = edge.get("first_step")
                try:
                    fs_int = int(fs)
                except Exception:
                    continue
                if fs_int <= threshold_step_num:
                    src = edge.get("source")
                    tgt = edge.get("target")
                    act = edge.get("action")
                    if src and tgt and act:
                        tmp_adj[src].append((act, tgt))
            adjacency_filtered = tmp_adj
    # Define BFS helper functions over the filtered adjacency for path and reachability queries
    def bfs_shortest_path(src: str, dst: str) -> Optional[int]:
        if src == dst:
            return 0
        if src not in adjacency_filtered or not adjacency_filtered.get(src):
            return None
        visited = set([src])
        dq = deque([(src, 0)])
        while dq:
            node, dist = dq.popleft()
            for act, nxt in adjacency_filtered.get(node, []):
                if nxt == dst:
                    return dist + 1
                if nxt not in visited:
                    visited.add(nxt)
                    dq.append((nxt, dist + 1))
        return None
    def reachable_within_filtered(src: str, max_steps: int) -> List[str]:
        if max_steps <= 0 or src not in adjacency_filtered:
            return []
        visited = set([src])
        reach = set()
        dq = deque([(src, 0)])
        while dq:
            node, dist = dq.popleft()
            if dist == max_steps:
                continue
            for act, nxt in adjacency_filtered.get(node, []):
                if nxt not in visited:
                    visited.add(nxt)
                    reach.add(nxt)
                    dq.append((nxt, dist + 1))
        return list(reach)

    # Helper to choose a contiguous range [L,R] according to difficulty
    def choose_range() -> Tuple[int, int]:
        if difficulty is None or difficulty <= 0 or difficulty >= n:
            return (0, n - 1)
        length = difficulty if difficulty <= n else n
        start = random.randint(0, n - length)
        return (start, start + length - 1)

    # Convert 0‑based index to actual step number (1‑based in logs), falling back to index+1
    def step_num(idx: int) -> int:
        if 0 <= idx < len(qa_utils.steps):
            return qa_utils.steps[idx]
        return idx + 1
    
    def openai_client(api_key: str, base_url: str):
        """
        Construct an OpenAI client.  This wrapper defers the import so
        that the dependency is optional until runtime.
        """
        try:
            from openai import OpenAI  # type: ignore
        except Exception as e:
            raise RuntimeError("openai package is required. Try: pip install openai") from e
        return OpenAI(api_key=api_key, base_url=base_url)

    def para(q: str) -> str:
        """
        Paraphrase a question string q if the paraphrase flag is enabled.

        In this generation function, paraphrasing is deferred to a separate
        batch post-processing step.  During question generation, this helper
        simply returns the original question without modification.
        """
        # Return the original question; actual paraphrasing is applied later.
        return q


    # Build candidate lists restricted to the first ``n`` steps.  Locations,
    # items and actions discovered outside this range are excluded from
    # consideration, ensuring that no question or answer relies on later
    # portions of the trajectory.
    candidate_locations: List[str] = []
    seen_locs: set[str] = set()
    for i in range(n):
        loc = qa_utils.locations[i]
        if loc and loc not in seen_locs:
            seen_locs.add(loc)
            candidate_locations.append(loc)
    # Candidate items: include items gained or carried within the first ``n`` steps
    candidate_items: List[str] = []
    # items gained
    for item, idxs in qa_utils.gain_events.items():
        for idx in idxs:
            if idx < n and item not in candidate_items:
                candidate_items.append(item)
                break
    # items in inventory
    for i in range(n):
        inv = qa_utils.inventory[i]
        if inv:
            for it in inv:
                if it not in candidate_items:
                    candidate_items.append(it)
    # Candidate actions: include only actions observed within the first ``n`` steps
    candidate_actions: List[str] = []
    seen_actions: set[str] = set()
    for i in range(n):
        act = qa_utils.actions[i]
        if act and act not in seen_actions:
            seen_actions.add(act)
            candidate_actions.append(act)

    # ------------------------------------------------------------------
    # Truncated helper functions for gains and location events
    # These helpers ensure that queries consider only steps within the first ``n``
    # steps of the trajectory when ``difficulty`` is positive.  If an event
    # occurs only after step ``n-1``, the functions return None.

    from collections import defaultdict as _defaultdict  # local alias to avoid clutter

    def first_gain_idx(item: str) -> Optional[int]:
        """Return the index (0-based) of the first time the specified item is gained within the first ``n`` steps.

        If the item is never gained within the truncated range, return None.
        """
        idxs = qa_utils.gain_events.get(item, [])
        for idx in idxs:
            if idx < n:
                return idx
        return None

    def nth_gain_idx(item: str, k: int) -> Optional[int]:
        """Return the index of the k‑th gain of the given item within the first ``n`` steps.

        If fewer than ``k`` gains occur before step ``n``, return None.
        """
        idxs = [idx for idx in qa_utils.gain_events.get(item, []) if idx < n]
        if len(idxs) >= k:
            return idxs[k - 1]
        return None

    def last_gain_idx(item: str) -> Optional[int]:
        """Return the index of the last gain of the given item within the first ``n`` steps.

        If the item is never gained within the truncated range, return None.
        """
        idxs = [idx for idx in qa_utils.gain_events.get(item, []) if idx < n]
        return idxs[-1] if idxs else None

    def first_enter_idx(loc: str) -> Optional[int]:
        """Return the first index where the player's location equals ``loc`` within the first ``n`` steps."""
        for i in range(n):
            if qa_utils.locations[i] == loc:
                return i
        return None

    def first_leave_idx(loc: str) -> Optional[int]:
        """Return the first index where the player leaves ``loc`` within the first ``n`` steps.

        A leave event is defined as the earliest step j (>0) such that
        ``locations[j-1] == loc`` and ``locations[j] != loc``.  If no such event
        occurs within the truncated range, return None.
        """
        for i in range(1, n):
            if qa_utils.locations[i - 1] == loc and qa_utils.locations[i] != loc:
                return i
        return None

    # Count how many items are gained per location within the first ``n`` steps.  This
    # dictionary is used for the F_location_most_item_gain tasks.  If a gain
    # occurs outside the truncated window, it is ignored.
    truncated_gain_locations: Dict[str, int] = _defaultdict(int)
    for itm, idxs in qa_utils.gain_events.items():
        for idx in idxs:
            if idx < n:
                loc = qa_utils.locations[idx]
                if loc:
                    truncated_gain_locations[loc] += 1

    # Keyword extraction
    location_tokens: set[str] = set()
    for loc in candidate_locations:
        if not loc:
            continue
        for part in re.findall(r"[a-zA-Z]{3,}", loc.lower()):
            location_tokens.add(part)

    # Build domain nouns from items, actions, and observation entities seen within the
    # truncation window.  Items and actions beyond the first ``n`` steps are ignored.
    items_vocab: set[str] = set()
    # items in inventory within range
    for i in range(n):
        inv = qa_utils.inventory[i]
        if inv:
            for it in inv:
                items_vocab.add(it.lower())
    # items gained within range
    for item, idxs in qa_utils.gain_events.items():
        for idx in idxs:
            if idx < n:
                items_vocab.add(str(item).lower())
                break
    # Objects from valid actions: take the second token when present, ignoring
    # directional commands and stop words
    objects_from_actions: set[str] = set()
    # Define synonyms to exclude direction-related nouns
    dir_synonyms = {
        "north","south","east","west","n","s","e","w",
        "northeast","ne","northwest","nw","southeast","se","southwest","sw",
        "up","u","down","d","in","out","inside","outside"
    }
    for i in range(n):
        acts = qa_utils.valid_actions[i]
        if acts:
            for a in acts:
                tokens = a.lower().split()
                if len(tokens) >= 2:
                    head = tokens[1]
                    if head not in dir_synonyms and len(head) >= 3:
                        objects_from_actions.add(head)
    # Observation nouns: capture words following articles (the/a/an) within range
    obs_nounish: set[str] = set()
    for i in range(n):
        obs = qa_utils.observations[i]
        if obs:
            for m in re.finditer(r"\b(?:the|a|an)\s+([a-z][a-z\-]{2,})\b", obs.lower()):
                obs_nounish.add(m.group(1))
    # Combine domain nouns and exclude location tokens
    domain_nouns = (items_vocab | objects_from_actions | obs_nounish) - location_tokens

    # Define a more comprehensive stopword list to filter out high-frequency
    # function words, verbs and boilerplate. 
    stopwords: set[str] = {
        "the", "and", "then", "open", "take", "go", "walk", "look", "enter",
        "for", "any", "just", "that", "might", "inside", "found", "opened",
        "information", "items", "item", "with", "without", "some", "into",
        "onto", "from", "there", "here", "make", "about", "been", "this", "what",
        "step", "steps", "reason", "observation", "keyword", "score", "location",
        "action", "player", "after", "before", "first", "second", "last", "gain",
        "leaves", "leaflet", "your", "you", "have", "has", "had", "having", "be",
        "am", "is", "are", "was", "were", "been", "being", "do", "does", "did",
        "doing", "can", "could", "may", "might", "must", "shall", "should", "will",
        "would", "again", "still", "just", "even", "over", "under", "around", "about",
        "onto", "around", "next", "continue", "need", "further", "area", "look",
        "examine", "try", "see"
    }
    # Minimum document frequency for a word to be considered (per reasoning/observation)
    MIN_DF_REASON = 3
    MIN_DF_OBS = 3

    # Candidate keywords from reasoning: gather word frequencies, prioritise domain nouns
    reason_df: Dict[str, int] = defaultdict(int)
    # Count keyword occurrences only within the first ``n`` reasoning sentences
    for i in range(n):
        reason = qa_utils.reasons[i]
        if not reason:
            continue
        words = set(re.findall(r"[a-z][a-z\-]{2,}", reason.lower()))
        for w in words:
            if w in stopwords or w in location_tokens:
                continue
            reason_df[w] += 1
    # Select domain nouns that appear in reasoning
    reason_domain = [w for w in domain_nouns if reason_df.get(w, 0) >= 1]
    # Select other high-frequency words exceeding DF threshold
    reason_common = [w for w, df in sorted(reason_df.items(), key=lambda x: -x[1]) if df >= MIN_DF_REASON]
    # Merge, preserving order and deduplicating
    candidate_reason_keywords: List[str] = []
    seen_kw: set[str] = set()
    for w in reason_domain + reason_common:
        if w not in seen_kw:
            candidate_reason_keywords.append(w)
            seen_kw.add(w)
    # Shuffle to diversify sampling and limit pool size (but large enough to sample later)
    random.shuffle(candidate_reason_keywords)
    candidate_reason_keywords = candidate_reason_keywords[: max(3 * max_per_type, 20)]

    # Candidate keywords from observations: similar extraction
    obs_df: Dict[str, int] = defaultdict(int)
    # Count keyword occurrences only within the first ``n`` observations
    for i in range(n):
        obs = qa_utils.observations[i]
        if not obs:
            continue
        words = set(re.findall(r"[a-z][a-z\-]{2,}", obs.lower()))
        for w in words:
            if w in stopwords or w in location_tokens:
                continue
            obs_df[w] += 1
    obs_domain = [w for w in domain_nouns if obs_df.get(w, 0) >= 1]
    obs_common = [w for w, df in sorted(obs_df.items(), key=lambda x: -x[1]) if df >= MIN_DF_OBS]
    candidate_obs_keywords: List[str] = []
    seen_obs: set[str] = set()
    for w in obs_domain + obs_common:
        if w not in seen_obs:
            candidate_obs_keywords.append(w)
            seen_obs.add(w)
    random.shuffle(candidate_obs_keywords)
    candidate_obs_keywords = candidate_obs_keywords[: max(3 * max_per_type, 20)]

    # For backward compatibility, retain 'candidate_keywords' as the reasoning keywords.
    candidate_keywords = candidate_reason_keywords.copy()

    # Helper to find occurrences of a keyword in reasons (exact word match)
    def reason_occurrences(keyword: str) -> List[int]:
        """Return indices of steps whose reasoning text contains the exact keyword.

        Matching is case‑insensitive and requires a word boundary on both sides.
        """
        kw = keyword.lower()
        positions: List[int] = []
        for i in range(n):
            reason = qa_utils.reasons[i]
            if not reason:
                continue
            if re.search(r"\b" + re.escape(kw) + r"\b", reason.lower()):
                positions.append(i)
        return positions

    # Helper to find occurrences of a keyword in observations (exact word match)
    def observation_occurrences(keyword: str) -> List[int]:
        """Return indices of steps whose observation contains the exact keyword.

        Matching is case‑insensitive and requires a word boundary on both sides.
        """
        kw = keyword.lower()
        positions: List[int] = []
        for i in range(n):
            obs = qa_utils.observations[i]
            if not obs:
                continue
            if re.search(r"\b" + re.escape(kw) + r"\b", obs.lower()):
                positions.append(i)
        return positions

    # Helper to compute visit counts and most visited locations in range [L,R]
    def visit_counts(L: int, R: int) -> Tuple[Dict[str, int], List[str]]:
        counts: Dict[str, int] = defaultdict(int)
        cur_loc = None
        for i in range(max(0, L), min(R, n - 1) + 1):
            loc = qa_utils.locations[i]
            if loc != cur_loc:
                if loc is not None:
                    counts[loc] += 1
                cur_loc = loc
        # Determine max visits
        if not counts:
            return counts, []
        max_visits = max(counts.values())
        most_visited = sorted([loc for loc, cnt in counts.items() if cnt == max_visits])
        return counts, most_visited

    # Helper to compute dwell counts and most dwell locations in range [L,R]
    def dwell_counts(L: int, R: int) -> Tuple[Dict[str, int], List[str]]:
        counts: Dict[str, int] = defaultdict(int)
        for i in range(max(0, L), min(R, n - 1) + 1):
            loc = qa_utils.locations[i]
            if loc:
                counts[loc] += 1
        if not counts:
            return counts, []
        max_dwell = max(counts.values())
        most_dwell = sorted([loc for loc, c in counts.items() if c == max_dwell])
        return counts, most_dwell

    # Deduplication helper
    def dedup_append(task_list: List[Dict[str, Any]], target: List[Dict[str, Any]], limit: int) -> None:
        seen: set = set()
        count = 0
        for t in task_list:
            key = (t["template"], t["question"])
            if key in seen:
                continue
            seen.add(key)
            target.append(t)
            count += 1
            if count >= limit:
                break

    # ----------------------------------------------------------------------
    # Single‑Hop Tasks
    # Template A_action: random steps asking for action
    tasks_A_action: List[Dict[str, Any]] = []
    step_indices = list(range(n))
    random.shuffle(step_indices)
    for idx in step_indices:
        act = qa_utils.actions[idx]
        q = f"At step {step_num(idx)}, what action did you execute?"
        a = act if act else "not answerable"
        tasks_A_action.append({"type": "Single‑Hop", "template": "A_action", "question": q, "paraphrase": para(q), "difficulty": 1, "range": [idx, idx], "gt": a})
    dedup_append(tasks_A_action, qas, max_per_type)

    # Template A_reason: random steps asking for first sentence of reasoning
    tasks_A_reason: List[Dict[str, Any]] = []
    random.shuffle(step_indices)
    for idx in step_indices:
        reason = qa_utils.reason_first_sentence[idx]
        q = f"At step {step_num(idx)}, what is the first sentence of your reasoning?"
        a = reason if reason else "not answerable"
        tasks_A_reason.append({"type": "Single‑Hop", "template": "A_reason", "question": q, "paraphrase": para(q), "difficulty": 1, "range": [idx, idx], "gt": a})
    dedup_append(tasks_A_reason, qas, max_per_type)

    # Template A_location: random steps asking for location
    tasks_A_location: List[Dict[str, Any]] = []
    random.shuffle(step_indices)
    for idx in step_indices:
        # Location before performing the action at this step
        loc = qa_utils.locations[idx]
        q = f"Before performing the action at step {step_num(idx)}, what is your location?"
        a = loc if loc else "not answerable"
        tasks_A_location.append({"type": "Single‑Hop", "template": "A_location", "question": q, "paraphrase": para(q), "difficulty": 1, "range": [idx, idx], "gt": a})
    dedup_append(tasks_A_location, qas, max_per_type)

    # Template A_reward: random steps asking for cumulative reward
    tasks_A_reward: List[Dict[str, Any]] = []
    random.shuffle(step_indices)
    for idx in step_indices:
        # Use cumulative reward at this step (reward after performing the action)
        rw = qa_utils.cum_rewards[idx] if idx < len(qa_utils.cum_rewards) else None
        q = f"After performing the action at step {step_num(idx)}, what is the cumulative reward so far?"
        a = str(rw) if rw is not None else "not answerable"
        tasks_A_reward.append({"type": "Single‑Hop", "template": "A_reward", "question": q, "paraphrase": para(q), "difficulty": 1, "range": [idx, idx], "gt": a})
    dedup_append(tasks_A_reward, qas, max_per_type)

    # Template A_keyword_occurrence: first/second/last/second last step whose reason contains keyword
    tasks_A_keyword: List[Dict[str, Any]] = []
    for kw in candidate_keywords:
        positions = reason_occurrences(kw)
        if not positions:
            # skip if keyword not found
            continue
        # first
        idx_first = positions[0]
        q = f"Which step is the first step whose reason mentions '{kw}'?"
        a = str(step_num(idx_first)) if idx_first is not None else "not answerable"
        tasks_A_keyword.append({"type": "Single‑Hop", "template": "A_keyword_occurrence", "question": q, "paraphrase": para(q), "difficulty": 1, "range": [0, n - 1], "gt": a})
        # second
        if len(positions) >= 2:
            idx_second = positions[1]
            q2 = f"Which step is the second step whose reason mentions '{kw}'?"
            a2 = str(step_num(idx_second))
        else:
            q2 = f"Which step is the second step whose reason mentions '{kw}'?"
            a2 = "not answerable"
        tasks_A_keyword.append({"type": "Single‑Hop", "template": "A_keyword_occurrence", "question": q2, "paraphrase": para(q2), "difficulty": 1, "range": [0, n - 1], "gt": a2})
        # last
        idx_last = positions[-1]
        q3 = f"Which step is the last step whose reason mentions '{kw}'?"
        a3 = str(step_num(idx_last))
        tasks_A_keyword.append({"type": "Single‑Hop", "template": "A_keyword_occurrence", "question": q3, "paraphrase": para(q3), "difficulty": 1, "range": [0, n - 1], "gt": a3})
        # second last
        if len(positions) >= 2:
            idx_second_last = positions[-2]
            q4 = f"Which step is the second last step whose reason mentions '{kw}'?"
            a4 = str(step_num(idx_second_last))
        else:
            q4 = f"Which step is the second last step whose reason mentions '{kw}'?"
            a4 = "not answerable"
        tasks_A_keyword.append({"type": "Single‑Hop", "template": "A_keyword_occurrence", "question": q4, "paraphrase": para(q4), "difficulty": 1, "range": [0, n - 1], "gt": a4})
    dedup_append(tasks_A_keyword, qas, max_per_type)

    # Template A_enter_leave: first enter/first leave/last enter for random locations
    tasks_A_enter_leave: List[Dict[str, Any]] = []
    random.shuffle(candidate_locations)
    for loc in candidate_locations:
        # Determine the first step where the player is at ``loc`` before performing the action
        idx_enter: Optional[int] = None
        for i in range(n):
            if qa_utils.locations[i] == loc:
                idx_enter = i
                break
        # Determine the first step where the player leaves ``loc`` (i.e., the first index j > 0
        # such that locations[j] != loc and locations[j-1] == loc)
        idx_leave: Optional[int] = None
        for i in range(1, n):
            if qa_utils.locations[i - 1] == loc and qa_utils.locations[i] != loc:
                idx_leave = i
                break
        # Determine the last enter step within the truncation window: the last index i
        # where locations[i] == loc and (i == 0 or locations[i-1] != loc)
        idx_last_enter: Optional[int] = None
        last_candidate: Optional[int] = None
        for i in range(n):
            if qa_utils.locations[i] == loc and (i == 0 or qa_utils.locations[i - 1] != loc):
                last_candidate = i
        idx_last_enter = last_candidate
        # first enter question (earliest time the player is at this location before acting)
        q = (
            f"At which step does the player first start being at '{loc}' "
            f"before performing the action?"
        )
        a = str(step_num(idx_enter)) if idx_enter is not None else "not answerable"
        tasks_A_enter_leave.append(
            {
                "type": "Single‑Hop",
                "template": "A_enter_leave",
                "question": q,
                "paraphrase": para(q),
                "difficulty": 1,
                "range": [0, n - 1],
                "gt": a,
            }
        )
        # first leave question (earliest time the player leaves this location before acting)
        q2 = (
            f"At which step does the player first leave '{loc}' "
            f"before performing the action?"
        )
        a2 = str(step_num(idx_leave)) if idx_leave is not None else "not answerable"
        tasks_A_enter_leave.append(
            {
                "type": "Single‑Hop",
                "template": "A_enter_leave",
                "question": q2,
                "paraphrase": para(q2),
                "difficulty": 1,
                "range": [0, n - 1],
                "gt": a2,
            }
        )
        # last enter question (latest time the player begins a stay at this location before acting)
        q3 = (
            f"At which step does the player last start being at '{loc}' "
            f"before performing the action?"
        )
        a3 = str(step_num(idx_last_enter)) if idx_last_enter is not None else "not answerable"
        tasks_A_enter_leave.append(
            {
                "type": "Single‑Hop",
                "template": "A_enter_leave",
                "question": q3,
                "paraphrase": para(q3),
                "difficulty": 1,
                "range": [0, n - 1],
                "gt": a3,
            }
        )
    dedup_append(tasks_A_enter_leave, qas, max_per_type)

    # Template A_gain_item: first/second/last gain of item
    tasks_A_gain_item: List[Dict[str, Any]] = []
    random.shuffle(candidate_items)
    for item in candidate_items:
        # Determine gain positions within the first ``n`` steps for this item
        idx_first = first_gain_idx(item)
        q = f"At which step did you first gain '{item}'?"
        a = str(step_num(idx_first)) if idx_first is not None else "not answerable"
        tasks_A_gain_item.append({"type": "Single‑Hop", "template": "A_gain_item", "question": q, "paraphrase": para(q), "difficulty": 1, "range": [0, n - 1], "gt": a})
        # second gain: second occurrence within truncated range
        idx_second = nth_gain_idx(item, 2)
        q2 = f"At which step did you gain '{item}' for the second time?"
        a2 = str(step_num(idx_second)) if idx_second is not None else "not answerable"
        tasks_A_gain_item.append({"type": "Single‑Hop", "template": "A_gain_item", "question": q2, "paraphrase": para(q2), "difficulty": 1, "range": [0, n - 1], "gt": a2})
        # last gain: last occurrence within truncated range
        idx_last = last_gain_idx(item)
        q3 = f"At which step did you gain '{item}' for the last time?"
        a3 = str(step_num(idx_last)) if idx_last is not None else "not answerable"
        tasks_A_gain_item.append({"type": "Single‑Hop", "template": "A_gain_item", "question": q3, "paraphrase": para(q3), "difficulty": 1, "range": [0, n - 1], "gt": a3})
    dedup_append(tasks_A_gain_item, qas, max_per_type)

    # Template A_valid_action: random step and pattern from actions
    tasks_A_valid_action: List[Dict[str, Any]] = []
    if candidate_actions:
        for pattern in candidate_actions:
            # sample some step indices for each pattern
            sampled_indices = random.sample(step_indices, min(max_per_type, n))
            for idx in sampled_indices:
                res = qa_utils.valid_actions_contain(idx, pattern)
                if res is None:
                    ans = "not answerable"
                else:
                    ans = "yes" if res else "no"
                q = (
                    f"At step {step_num(idx)}, is "
                    f"'{pattern}' a valid action? Answer in 'yes' or 'no'"
                )
                tasks_A_valid_action.append(
                    {
                        "type": "Single‑Hop",
                        "template": "A_valid_action",
                        "question": q,
                        "paraphrase": para(q),
                        "difficulty": 1,
                        "range": [idx, idx],
                        "gt": ans,
                    }
                )
        dedup_append(tasks_A_valid_action, qas, max_per_type)

    # Template A_obs_before_after: random steps asking for observation before/after
    tasks_A_obs: List[Dict[str, Any]] = []
    sampled_indices = random.sample(step_indices, min(max_per_type, n))
    for idx in sampled_indices:
        # after
        after_obs = qa_utils.env_feedback[idx]
        # Observation after the action
        if after_obs:
            q = (
                f"At step {step_num(idx)}, what observation did you see after "
                f"performing the action?"
            )
            a = after_obs.strip()
            tasks_A_obs.append(
                {
                    "type": "Single‑Hop",
                    "template": "A_obs_after",
                    "question": q,
                    "paraphrase": para(q),
                    "difficulty": 1,
                    "range": [idx, idx],
                    "gt": a,
                }
            )
        else:
            q = (
                f"At step {step_num(idx)}, what observation did you see after "
                f"performing the action?"
            )
            a = "not answerable"
            tasks_A_obs.append(
                {
                    "type": "Single‑Hop",
                    "template": "A_obs_after",
                    "question": q,
                    "paraphrase": para(q),
                    "difficulty": 1,
                    "range": [idx, idx],
                    "gt": a,
                }
            )
        # Observation before the action (from previous env_feedback)
        if idx > 0:
            before_obs = qa_utils.env_feedback[idx - 1]
            if before_obs:
                q2 = (
                    f"At step {step_num(idx)}, what observation did you see before "
                    f"performing the action?"
                )
                a2 = before_obs.strip()
                tasks_A_obs.append(
                    {
                        "type": "Single‑Hop",
                        "template": "A_obs_before",
                        "question": q2,
                        "paraphrase": para(q2),
                        "difficulty": 1,
                        "range": [idx, idx],
                        "gt": a2,
                    }
                )
            else:
                q2 = (
                    f"At step {step_num(idx)}, what observation did you see before "
                    f"performing the action?"
                )
                a2 = "not answerable"
                tasks_A_obs.append(
                    {
                        "type": "Single‑Hop",
                        "template": "A_obs_before",
                        "question": q2,
                        "paraphrase": para(q2),
                        "difficulty": 1,
                        "range": [idx, idx],
                        "gt": a2,
                    }
                )
    dedup_append(tasks_A_obs, qas, max_per_type)

    # ----------------------------------------------------------------------
    # Multi‑Hop Tasks
    # B_keyword_after_* templates: for each keyword and occurrence type and delta we ask for action/location/score/observation
    occurrence_names = ["first", "second", "last", "second last"]
    # Map occurrence name to index function
    def get_occurrence_index(positions: List[int], name: str) -> Optional[int]:
        if not positions:
            return None
        if name == "first":
            return positions[0]
        if name == "second":
            return positions[1] if len(positions) >= 2 else None
        if name == "last":
            return positions[-1]
        if name == "second last":
            return positions[-2] if len(positions) >= 2 else None
        return None

    # ------------------------------------------------------------------
    # Multi‑Hop keyword‑based tasks

    # Function to add keyword‑based multi‑hop tasks for a given set of occurrences.
    def add_keyword_multi_hop_tasks(keyword: str, positions: List[int], context: str) -> None:
        """Append multi‑hop tasks for the given keyword and occurrence positions.
        """
        if not positions:
            return
        # For each occurrence type (first, second, last, second last)
        for occ_name in occurrence_names:
            pos_idx = get_occurrence_index(positions, occ_name)
            if pos_idx is None:
                continue

            max_delta_range = min(4, n - pos_idx)
            if max_delta_range <= 1:
                possible_deltas = [1]
            else:
                possible_deltas = list(range(1, max_delta_range))
            # Sample up to 3 deltas for diversity
            sampled_deltas = possible_deltas[:3]
            for delta in sampled_deltas:
                target = pos_idx + delta
                # Build question prefix depending on context
                if context == "reason":
                    prefix = f"After the {occ_name} step whose reason mentions '{keyword}',"
                else:
                    prefix = f"After the {occ_name} step whose observation mentions '{keyword}',"
                # Action: query the action executed delta steps later
                q_act = f"{prefix} what action is executed {delta} step(s) later?"
                if target < n and qa_utils.actions[target]:
                    ans_act = qa_utils.actions[target]
                    typ = "Multi‑Hop"
                else:
                    ans_act = "not answerable"
                    typ = "Adversarial"
                qas.append({"type": typ, "template": "B_keyword_after_action", "question": q_act, "paraphrase": para(q_act), "difficulty": delta + 1, "range": [pos_idx, min(n - 1, pos_idx + delta)], "gt": ans_act})
                # Location: ask for the location before performing the action at the target step
                q_loc = f"{prefix} what is the location before performing the action {delta} step(s) later?"
                if target < n and qa_utils.locations[target]:
                    ans_loc = qa_utils.locations[target]
                    typ2 = "Multi‑Hop"
                else:
                    ans_loc = "not answerable"
                    typ2 = "Adversarial"
                qas.append({"type": typ2, "template": "B_keyword_after_location", "question": q_loc, "paraphrase": para(q_loc), "difficulty": delta + 1, "range": [pos_idx, min(n - 1, pos_idx + delta)], "gt": ans_loc})
                # Reward: ask for the cumulative reward after performing the action at the target step
                q_sc = f"{prefix} what is the cumulative reward after performing the action {delta} step(s) later?"
                if target < n:
                    ans_sc = str(qa_utils.cum_rewards[target])
                    typ3 = "Multi‑Hop"
                else:
                    ans_sc = "not answerable"
                    typ3 = "Adversarial"
                qas.append({"type": typ3, "template": "B_keyword_after_reward", "question": q_sc, "paraphrase": para(q_sc), "difficulty": delta + 1, "range": [pos_idx, min(n - 1, pos_idx + delta)], "gt": ans_sc})
                # Observation: ask for the observation seen after performing the action at the target step
                q_obs = f"{prefix} what observation is seen after performing the action {delta} step(s) later?"
                if target < n and qa_utils.env_feedback[target]:
                    ans_obs = qa_utils.env_feedback[target].strip()
                    typ4 = "Multi‑Hop"
                else:
                    ans_obs = "not answerable"
                    typ4 = "Adversarial"
                qas.append({"type": typ4, "template": "B_keyword_after_observation", "question": q_obs, "paraphrase": para(q_obs), "difficulty": delta + 1, "range": [pos_idx, min(n - 1, pos_idx + delta)], "gt": ans_obs})
                # Ensure we do not exceed max_per_type per keyword: count tasks for action template containing the keyword
                count = sum(1 for t in qas if t.get("template") == "B_keyword_after_action" and keyword in t["question"])
                if count >= max_per_type:
                    break
            # Additional break if limit reached
            count = sum(1 for t in qas if t.get("template") == "B_keyword_after_action" and keyword in t["question"])
            if count >= max_per_type:
                break

    # Generate multi‑hop tasks for keywords in reasoning
    for kw in candidate_reason_keywords[:max_per_type]:
        positions = reason_occurrences(kw)
        add_keyword_multi_hop_tasks(kw, positions, context="reason")

    # Generate multi‑hop tasks for keywords in observations
    for kw in candidate_obs_keywords[:max_per_type]:
        positions = observation_occurrences(kw)
        add_keyword_multi_hop_tasks(kw, positions, context="obs")

    # B_gain_item_after_* tasks (first gain → lookahead). 
    shuffled_items = candidate_items.copy()
    random.shuffle(shuffled_items)
    for item in shuffled_items[:max_per_type]:
        idx_first_gain = first_gain_idx(item)
        if idx_first_gain is None:
            continue
        # Determine allowable deltas (at least 1, at most 10, capped by remaining steps)
        max_allowed = min(10, n - idx_first_gain)
        if max_allowed <= 1:
            possible_deltas = [1]
        else:
            possible_deltas = list(range(1, max_allowed))
        # Sample up to 3 deltas for this item for diversity
        sampled_deltas = possible_deltas
        if len(sampled_deltas) > 3:
            sampled_deltas = random.sample(sampled_deltas, 3)
        for delta in sorted(sampled_deltas):
            target = idx_first_gain + delta
            prefix = f"After obtaining '{item}' for the first time,"
            # Reward: cumulative reward after performing the action at the target step
            q_sc = f"{prefix} what is the cumulative reward after performing the action {delta} step(s) later?"
            if target < n:
                ans_sc = str(qa_utils.cum_rewards[target])
                typ = "Multi‑Hop"
            else:
                ans_sc = "not answerable"
                typ = "Adversarial"
            qas.append({"type": typ, "template": "B_gain_after_reward", "question": q_sc, "paraphrase": para(q_sc), "difficulty": delta + 1, "range": [idx_first_gain, min(n - 1, target)], "gt": ans_sc})
            # Location: location before performing the action at the target step
            q_loc = f"{prefix} what is the location before performing the action {delta} step(s) later?"
            if target < n and qa_utils.locations[target]:
                ans_loc = qa_utils.locations[target]
                typ2 = "Multi‑Hop"
            else:
                ans_loc = "not answerable"
                typ2 = "Adversarial"
            qas.append({"type": typ2, "template": "B_gain_after_location", "question": q_loc, "paraphrase": para(q_loc), "difficulty": delta + 1, "range": [idx_first_gain, min(n - 1, target)], "gt": ans_loc})
            # Action: action executed at the target step
            q_act = f"{prefix} what action is executed {delta} step(s) later?"
            if target < n and qa_utils.actions[target]:
                ans_act = qa_utils.actions[target]
                typ3 = "Multi‑Hop"
            else:
                ans_act = "not answerable"
                typ3 = "Adversarial"
            qas.append({"type": typ3, "template": "B_gain_after_action", "question": q_act, "paraphrase": para(q_act), "difficulty": delta + 1, "range": [idx_first_gain, min(n - 1, target)], "gt": ans_act})
            # Observation: observation seen after performing the action at the target step
            q_obs = f"{prefix} what observation is seen after performing the action {delta} step(s) later?"
            if target < n and qa_utils.env_feedback[target]:
                ans_obs = qa_utils.env_feedback[target].strip()
                typ4 = "Multi‑Hop"
            else:
                ans_obs = "not answerable"
                typ4 = "Adversarial"
            qas.append({"type": typ4, "template": "B_gain_after_observation", "question": q_obs, "paraphrase": para(q_obs), "difficulty": delta + 1, "range": [idx_first_gain, min(n - 1, target)], "gt": ans_obs})
        # End of deltas loop

    # ----------------------------------------------------------------------
    # Inducing tasks
    # C_keyword_count: count occurrences of keywords in observations and in reasoning
    # For observation keywords:
    if difficulty <= 0:
        # global tasks for observations for the top keywords
        for kw in candidate_obs_keywords[:max_per_type]:
            count = qa_utils.keyword_count_in_obs(kw, 0, n - 1)
            q = f"How many observations mention '{kw}'?"
            qas.append({"type": "Inducing", "template": "C_keyword_count_obs", "question": q, "paraphrase": para(q), "difficulty": -1, "range": [0, n - 1], "gt": count})
    else:
        # positive difficulty: select up to max_per_type keywords and assign one range to each
        obs_kws = candidate_obs_keywords.copy()
        random.shuffle(obs_kws)
        for kw in obs_kws[:max_per_type]:
            L, R = choose_range()
            count = qa_utils.keyword_count_in_obs(kw, L, R)
            q = f"From steps {step_num(L)} to {step_num(R)}, how many observations mention '{kw}'?"
            qas.append({"type": "Inducing", "template": "C_keyword_count_obs", "question": q, "paraphrase": para(q), "difficulty": R - L + 1, "range": [L, R], "gt": count})
    # For reasoning keywords:
    if difficulty <= 0:
        for kw in candidate_reason_keywords[:max_per_type]:
            positions = reason_occurrences(kw)
            count = len(positions)
            q = f"How many reasoning sentences mention '{kw}'?"
            qas.append({"type": "Inducing", "template": "C_keyword_count_reason", "question": q, "paraphrase": para(q), "difficulty": -1, "range": [0, n - 1], "gt": count})
    else:
        reason_kws = candidate_reason_keywords.copy()
        random.shuffle(reason_kws)
        for kw in reason_kws[:max_per_type]:
            positions = reason_occurrences(kw)
            L, R = choose_range()
            count = len([i for i in positions if L <= i <= R])
            q = f"From steps {step_num(L)} to {step_num(R)}, how many reasoning sentences mention '{kw}'?"
            qas.append({"type": "Inducing", "template": "C_keyword_count_reason", "question": q, "paraphrase": para(q), "difficulty": R - L + 1, "range": [L, R], "gt": count})

    # C_action_mode: most frequent action taken
    # global
    if difficulty <= 0:
        # compute full range
        action_counts: Dict[str, int] = defaultdict(int)
        for act in qa_utils.actions:
            if act:
                action_counts[act] += 1
        if action_counts:
            max_count = max(action_counts.values())
            mode_actions = sorted([act for act, c in action_counts.items() if c == max_count])
            ans = mode_actions if len(mode_actions) > 1 else mode_actions[0]
        else:
            ans = "not answerable"
        q = "What is the most frequent action taken?"
        qas.append({"type": "Inducing", "template": "C_action_mode", "question": q, "paraphrase": para(q), "difficulty": -1, "range": [0, n - 1], "gt": ans})
    # range tasks
    if difficulty > 0:
        for _ in range(max_per_type):
            L, R = choose_range()
            action_counts: Dict[str, int] = defaultdict(int)
            for i in range(L, R + 1):
                act = qa_utils.actions[i]
                if act:
                    action_counts[act] += 1
            if action_counts:
                max_count = max(action_counts.values())
                mode_actions = sorted([act for act, c in action_counts.items() if c == max_count])
                ans = mode_actions if len(mode_actions) > 1 else mode_actions[0]
            else:
                ans = "not answerable"
            q = f"From steps {step_num(L)} to {step_num(R)}, what is the most frequent action taken?"
            qas.append({"type": "Inducing", "template": "C_action_mode", "question": q, "paraphrase": para(q), "difficulty": R - L + 1, "range": [L, R], "gt": ans})

    # C_distinct_locations: count distinct locations visited
    if difficulty <= 0:
        distinct_count_global, _ = qa_utils.locations_stats_in_range(0, n - 1)
        q = "How many distinct locations were visited?"
        qas.append({"type": "Inducing", "template": "C_distinct_locations", "question": q, "paraphrase": para(q), "difficulty": -1, "range": [0, n - 1], "gt": distinct_count_global})
        # most frequent visited location using visit counts
        _, most_visited_global = visit_counts(0, n - 1)
        q2 = "What is the most frequently visited location?"
        ans2 = most_visited_global if len(most_visited_global) > 1 else (most_visited_global[0] if most_visited_global else "not answerable")
        qas.append({"type": "Inducing", "template": "C_most_frequent_location", "question": q2, "paraphrase": para(q2), "difficulty": -1, "range": [0, n - 1], "gt": ans2})
    if difficulty > 0:
        for _ in range(max_per_type):
            L, R = choose_range()
            distinct_count, most_visited = visit_counts(L, R)
            distinct_num = len(distinct_count)
            q1 = f"From steps {step_num(L)} to {step_num(R)}, how many distinct locations were visited?"
            qas.append({"type": "Inducing", "template": "C_distinct_locations", "question": q1, "paraphrase": para(q1), "difficulty": R - L + 1, "range": [L, R], "gt": distinct_num})
            q2 = f"From steps {step_num(L)} to {step_num(R)}, what is the most frequently visited location?"
            ans2 = most_visited if len(most_visited) > 1 else (most_visited[0] if most_visited else "not answerable")
            qas.append({"type": "Inducing", "template": "C_most_frequent_location", "question": q2, "paraphrase": para(q2), "difficulty": R - L + 1, "range": [L, R], "gt": ans2})

    # C_total_dwell: longest total dwell time per location
    if difficulty <= 0:
        _, most_dwell_global = dwell_counts(0, n - 1)
        q = "Which is the location with the longest duration of stay in total?"
        ans = most_dwell_global if len(most_dwell_global) > 1 else (most_dwell_global[0] if most_dwell_global else "not answerable")
        qas.append({"type": "Inducing", "template": "C_total_dwell", "question": q, "paraphrase": para(q), "difficulty": -1, "range": [0, n - 1], "gt": ans})
    if difficulty > 0:
        for _ in range(max_per_type):
            L, R = choose_range()
            _, most_dwell = dwell_counts(L, R)
            q = f"From steps {step_num(L)} to {step_num(R)}, which is the location with the longest duration of stay in total?"
            ans = most_dwell if len(most_dwell) > 1 else (most_dwell[0] if most_dwell else "not answerable")
            qas.append({"type": "Inducing", "template": "C_total_dwell", "question": q, "paraphrase": para(q), "difficulty": R - L + 1, "range": [L, R], "gt": ans})


    # ----------------------------------------------------------------------
    # Spatial Tasks
    # D_shortest_path: random pairs of steps.  Use BFS over the filtered adjacency
    tasks_D_shortest: List[Dict[str, Any]] = []
    if n > 1:
        for _ in range(max_per_type * 2):
            i_idx, j_idx = random.sample(range(n), 2)
            loc1 = qa_utils.locations[i_idx]
            loc2 = qa_utils.locations[j_idx]
            if not loc1 or not loc2 or loc1 == loc2:
                continue
            dist = bfs_shortest_path(loc1, loc2)
            ans = dist if dist is not None else "not answerable"
            typ = "Spatial" if dist is not None else "Adversarial"
            q = f"What is the shortest path length between the locations at steps {step_num(i_idx)} and {step_num(j_idx)}?"
            tasks_D_shortest.append({"type": typ, "template": "D_shortest_path", "question": q, "paraphrase": para(q), "difficulty": max(abs(j_idx - i_idx), 1), "range": [min(i_idx, j_idx), max(i_idx, j_idx)], "gt": ans})
            if len(tasks_D_shortest) >= max_per_type:
                break
    dedup_append(tasks_D_shortest, qas, max_per_type)

    # D_reachable_within
    tasks_D_reachable: List[Dict[str, Any]] = []
    for _ in range(max_per_type * 2):
        idx = random.randint(0, n - 1)
        src_loc = qa_utils.locations[idx]
        if not src_loc:
            continue
        # choose target different from current
        tgt_locs = [l for l in candidate_locations if l != src_loc]
        if not tgt_locs:
            continue
        tgt = random.choice(tgt_locs)
        N = random.randint(1, 3)
        path_len = bfs_shortest_path(src_loc, tgt)
        if path_len is not None and path_len <= N:
            ans = "yes"
        else:
            ans = "no"
        typ = "Spatial"
        q = f"At step {step_num(idx)}, is it possible to reach '{tgt}' within {N} steps? Answer in 'yes' or 'no'"
        tasks_D_reachable.append({"type": typ, "template": "D_reachable_within", "question": q, "paraphrase": para(q), "difficulty": N + 1, "range": [idx, min(n - 1, idx + N)], "gt": ans})
        if len(tasks_D_reachable) >= max_per_type:
            break
    dedup_append(tasks_D_reachable, qas, max_per_type)

    # D_direction_count: random steps asking for number of distinct directions
    tasks_D_dircount: List[Dict[str, Any]] = []
    for _ in range(max_per_type * 2):
        idx = random.randint(0, n - 1)
        loc = qa_utils.locations[idx]
        if not loc:
            continue
        dirs = set()
        for act, tgt in adjacency_filtered.get(loc, []):
            d = qa_utils.direction_of_action(act)
            if d and d in qa_utils.PURE_DIRECTIONS:
                dirs.add(d)
        count_dirs = len(dirs)
        q = f"At step {step_num(idx)}, how many distinct directions can you move from your current location based on your knowledge?"
        tasks_D_dircount.append({"type": "Spatial", "template": "D_direction_count", "question": q, "paraphrase": para(q), "difficulty": 1, "range": [idx, idx], "gt": count_dirs})
        if len(tasks_D_dircount) >= max_per_type:
            break
    dedup_append(tasks_D_dircount, qas, max_per_type)

    # D_reachable_locations_count
    tasks_D_reachcount: List[Dict[str, Any]] = []
    for _ in range(max_per_type * 2):
        idx = random.randint(0, n - 1)
        loc = qa_utils.locations[idx]
        if not loc:
            continue
        N = random.randint(1, 3)
        reachable_set = reachable_within_filtered(loc, N)
        # Exclude the current location itself from the count
        count = len([x for x in reachable_set if x != loc])
        q = f"At step {step_num(idx)}, excluding your current location, how many distinct locations are reachable within {N} steps?"
        tasks_D_reachcount.append({"type": "Spatial", "template": "D_reachable_locations_count", "question": q, "paraphrase": para(q), "difficulty": N + 1, "range": [idx, min(n - 1, idx + N)], "gt": count})
        if len(tasks_D_reachcount) >= max_per_type:
            break
    dedup_append(tasks_D_reachcount, qas, max_per_type)

    # D_compare_distances
    tasks_D_compare: List[Dict[str, Any]] = []
    if len(candidate_locations) >= 3:
        for _ in range(max_per_type * 2):
            idx = random.randint(0, n - 1)
            curr_loc = qa_utils.locations[idx]
            if not curr_loc:
                continue
            # choose two distinct target locations not equal current
            targets = [l for l in candidate_locations if l != curr_loc]
            if len(targets) < 2:
                continue
            A, B = random.sample(targets, 2)
            distA = bfs_shortest_path(curr_loc, A)
            distB = bfs_shortest_path(curr_loc, B)
            if distA is None and distB is None:
                ans = "not answerable"
            elif distA is None:
                ans = B
            elif distB is None:
                ans = A
            else:
                if distA < distB:
                    ans = A
                elif distB < distA:
                    ans = B
                else:
                    ans = "not answerable"
            q = f"From the location at step {step_num(idx)}, which is closer in terms of fewer steps to reach, '{A}' or '{B}'?"
            # Determine difficulty as the greater distance among the two, defaulting to 1 for unreachable paths
            max_d = 0
            if distA is not None:
                max_d = max(max_d, distA)
            if distB is not None:
                max_d = max(max_d, distB)
            difficulty_value = max(max_d, 1)
            tasks_D_compare.append({"type": "Spatial", "template": "D_compare_distances", "question": q, "paraphrase": para(q), "difficulty": difficulty_value, "range": [idx, idx], "gt": ans})
            if len(tasks_D_compare) >= max_per_type:
                break
    dedup_append(tasks_D_compare, qas, max_per_type)

    # D_sequence_moves
    tasks_D_seq: List[Dict[str, Any]] = []
    for _ in range(max_per_type * 3):
        idx = random.randint(0, n - 1)
        start_loc = qa_utils.locations[idx]
        if not start_loc:
            continue
        # Attempt to build a sequence of up to length 3 using directional actions
        seq: List[str] = []
        curr_loc = start_loc
        reachable = True
        for step_count in range(3):
            # find all directional actions from current location in the filtered adjacency
            possible: List[Tuple[str, str]] = []
            for act, tgt in adjacency_filtered.get(curr_loc, []):
                d = qa_utils.direction_of_action(act)
                if d and d in qa_utils.PURE_DIRECTIONS:
                    possible.append((d, tgt))
            if not possible:
                reachable = False
                break
            d, tgt = random.choice(possible)
            seq.append(d)
            curr_loc = tgt
        q = f"At step {step_num(idx)}, if you move {', then '.join(seq)}, which location do you reach?"
        ans = curr_loc if reachable else "not answerable"
        typ = "Spatial" if reachable else "Adversarial"
        tasks_D_seq.append({"type": typ, "template": "D_sequence_moves", "question": q, "paraphrase": para(q), "difficulty": len(seq) if seq else 1, "range": [idx, idx], "gt": ans})
        if len(tasks_D_seq) >= max_per_type:
            break
    dedup_append(tasks_D_seq, qas, max_per_type)

    # ----------------------------------------------------------------------
    # Time Tasks
    # E_scene_order: random pairs of locations.  Use truncated indices
    tasks_E_scene_order: List[Dict[str, Any]] = []
    if len(candidate_locations) >= 2:
        for _ in range(max_per_type * 2):
            A, B = random.sample(candidate_locations, 2)
            idx_A = first_enter_idx(A)
            idx_B = first_enter_idx(B)
            if idx_A is None or idx_B is None:
                ans = "not answerable"
            else:
                ans = "yes" if idx_B < idx_A else "no"
            q = f"Before first time entering '{A}', have you ever been to '{B}'? Answer in 'yes' or 'no'"
            tasks_E_scene_order.append({"type": "Time", "template": "E_scene_order", "question": q, "paraphrase": para(q), "difficulty": 1, "range": [0, n - 1], "gt": ans})
            if len(tasks_E_scene_order) >= max_per_type:
                break
    dedup_append(tasks_E_scene_order, qas, max_per_type)

    # E_gain_delay: first gain to cumulative reward increase delay (truncated)
    tasks_E_gain_delay: List[Dict[str, Any]] = []
    for item in candidate_items[:4]:
        gi = first_gain_idx(item)
        if gi is None:
            continue
        # find next index within the first n steps where cumulative reward strictly increases
        delay = None
        base = qa_utils.cum_rewards[gi]
        for j in range(gi + 1, n):
            if qa_utils.cum_rewards[j] > base:
                delay = j - gi
                break
        ans = delay if delay is not None else "not answerable"
        end_idx = gi + delay if (delay is not None) else gi
        q = f"After the step which you first gained '{item}', how many steps later does the cumulative reward increase for the first time?"
        tasks_E_gain_delay.append({"type": "Time", "template": "E_gain_delay", "question": q, "paraphrase": para(q), "difficulty": 1, "range": [gi, min(n - 1, end_idx)], "gt": ans})
        if len(tasks_E_gain_delay) >= max_per_type:
            break
    dedup_append(tasks_E_gain_delay, qas, max_per_type)

    # E_region_stay: For each unique location, ask for the contiguous stay length after first entering (truncated)
    tasks_E_region_stay: List[Dict[str, Any]] = []
    # Limit to at most max_per_type locations; if there are fewer, ask for each.
    loc_list = candidate_locations.copy()
    random.shuffle(loc_list)
    for loc in loc_list:
        enter_idx = first_enter_idx(loc)
        leave_idx = first_leave_idx(loc)
        if enter_idx is None or leave_idx is None or leave_idx <= enter_idx:
            ans = "not answerable"
            rng = [0, n - 1]
        else:
            dur = leave_idx - enter_idx
            ans = dur
            rng = [enter_idx, leave_idx]
        q = f"After first time entering '{loc}', how many steps did you stay in this location?"
        tasks_E_region_stay.append({"type": "Time", "template": "E_region_stay", "question": q, "paraphrase": para(q), "difficulty": 1, "range": rng, "gt": ans})
        if len(tasks_E_region_stay) >= max_per_type:
            break
    dedup_append(tasks_E_region_stay, qas, max_per_type)

    # E_item_order: random pairs of items (truncated)
    tasks_E_item_order: List[Dict[str, Any]] = []
    if len(candidate_items) >= 2:
        for _ in range(max_per_type * 2):
            A, B = random.sample(candidate_items, 2)
            idx_A = first_gain_idx(A)
            idx_B = first_gain_idx(B)
            if idx_A is None or idx_B is None:
                ans = "not answerable"
            else:
                ans = "yes" if idx_B < idx_A else "no"
            q = f"Before first time obtaining '{A}', have you ever obtained '{B}'? Answer in 'yes' or 'no'"
            tasks_E_item_order.append({"type": "Time", "template": "E_item_order", "question": q, "paraphrase": para(q), "difficulty": 1, "range": [0, n - 1], "gt": ans})
            if len(tasks_E_item_order) >= max_per_type:
                break
    dedup_append(tasks_E_item_order, qas, max_per_type)

    # E_item_before_leave: determine if player leaves a location before gaining an item (truncated)
    tasks_E_item_before_leave: List[Dict[str, Any]] = []
    for item in candidate_items[:4]:
        for loc in candidate_locations[:4]:
            gi = first_gain_idx(item)
            li = first_leave_idx(loc)
            if gi is None or li is None:
                ans = "not answerable"
            else:
                ans = "yes" if li < gi else "no"
            q = f"Before first time obtaining '{item}', have you ever left '{loc}'? Answer in 'yes' or 'no'"
            tasks_E_item_before_leave.append({"type": "Time", "template": "E_item_before_leave", "question": q, "paraphrase": para(q), "difficulty": 1, "range": [0, n - 1], "gt": ans})
            if len(tasks_E_item_before_leave) >= max_per_type:
                break
        if len(tasks_E_item_before_leave) >= max_per_type:
            break
    dedup_append(tasks_E_item_before_leave, qas, max_per_type)

    # F_list_inventory: list items carried after executing step idx.
    tasks_F_list_inventory: List[Dict[str, Any]] = []
    random.shuffle(step_indices)
    for idx in step_indices:
        # Determine inventory after performing step idx
        inv_after = qa_utils.inventory[idx + 1] if (idx + 1) < n else None
        if inv_after:
            ans_str = ", ".join(inv_after)
        else:
            ans_str = "not answerable"
        q = f"After performing the action at step {step_num(idx)}, what are all the items you carried?"
        tasks_F_list_inventory.append({
            "type": "Logical",
            "template": "F_list_inventory",
            "question": q,
            "paraphrase": para(q),
            "difficulty": 1,
            "range": [idx, idx],
            "gt": ans_str,
        })
        if len(tasks_F_list_inventory) >= max_per_type:
            break
    dedup_append(tasks_F_list_inventory, qas, max_per_type)

    # F_max_inventory_step: identify the step after which the player carries the most items.
    max_inv_count = -1
    max_inv_idx = None
    for i in range(n):
        inv_after = qa_utils.inventory[i + 1] if (i + 1) < n else qa_utils.inventory[i]
        cnt = len(inv_after) if inv_after else 0
        if cnt > max_inv_count:
            max_inv_count = cnt
            max_inv_idx = i
    if max_inv_idx is not None:
        q = "After completing which step does the inventory contain the most items?"
        a = str(step_num(max_inv_idx))
        qas.append({"type": "Logical", "template": "F_max_inventory_step", "question": q, "paraphrase": para(q), "difficulty": 1, "range": [0, n - 1], "gt": a})

    # F_location_most_item_gain: determine location with the most item gains within truncated range
    if truncated_gain_locations:
        max_gain = max(truncated_gain_locations.values())
        top_locs = sorted([loc for loc, c in truncated_gain_locations.items() if c == max_gain])
        ans = top_locs if len(top_locs) > 1 else (top_locs[0] if top_locs else "not answerable")
        q = "Within the observed steps, at which location did you pick up the largest number of new items?"
        qas.append({"type": "Logical", "template": "F_location_most_item_gain", "question": q, "paraphrase": para(q), "difficulty": 1, "range": [0, n - 1], "gt": ans})

    # F_has_item: ask whether the player is carrying a specific item after a given step.
    tasks_F_has_item: List[Dict[str, Any]] = []
    if candidate_items:
        # Make a pool of candidate (step, item) pairs for diversity
        pairs: List[Tuple[int, str]] = []
        for _ in range(len(step_indices) * 2):
            idx = random.randint(0, n - 1)
            item = random.choice(candidate_items)
            pairs.append((idx, item))
        random.shuffle(pairs)
        for idx, item in pairs:
            inv_after = qa_utils.inventory[idx + 1] if (idx + 1) < n else None
            if inv_after is None:
                ans = "not answerable"
                typ = "Logical"
            else:
                ans = "yes" if (item in inv_after) else "no"
                typ = "Logical"
            q = f"After performing the action at step {step_num(idx)}, did you have '{item}' in inventory? Answer in 'yes' or 'no'"
            tasks_F_has_item.append({"type": typ, "template": "F_has_item", "question": q, "paraphrase": para(q), "difficulty": 1, "range": [idx, idx], "gt": ans})
            if len(tasks_F_has_item) >= max_per_type:
                break
        dedup_append(tasks_F_has_item, qas, max_per_type)


    # start of adversarial section
    # -------------------------------
    # Adversarial (FULL)
    # -------------------------------

    # Per-log "without replacement" tracking for negatives
    used_neg_items = set()
    used_neg_locs = set()

    # -------------------------------
    # Adversarial: keyword mismatch (keep original)
    # -------------------------------
    obs_not_in_reason = [kw for kw in candidate_obs_keywords if not reason_occurrences(kw)]
    reason_not_in_obs = [kw for kw in candidate_reason_keywords if not observation_occurrences(kw)]

    for kw in obs_not_in_reason[:max_per_type]:
        q = f"Which step is the first step whose reason mentions '{kw}'?"
        qas.append({
            "type": "Adversarial",
            "template": "G_keyword_occurrence_adversarial_reason",
            "question": q,
            "paraphrase": para(q),
            "difficulty": n,
            "range": [0, n - 1],
            "gt": "not answerable",
        })

    for kw in reason_not_in_obs[:max_per_type]:
        q = f"Which step is the first step whose observation mentions '{kw}'?"
        qas.append({
            "type": "Adversarial",
            "template": "G_keyword_occurrence_adversarial_observation",
            "question": q,
            "paraphrase": para(q),
            "difficulty": n,
            "range": [0, n - 1],
            "gt": "not answerable",
        })

    # -------------------------------
    # Adversarial: shortest path tasks (keep original)
    # -------------------------------
    if len(candidate_locations) >= 2:
        pairs_tried = 0
        for loc1 in candidate_locations:
            for loc2 in candidate_locations:
                if loc1 == loc2:
                    continue
                if bfs_shortest_path(loc1, loc2) is None:
                    q = f"What is the shortest path length from '{loc1}' to '{loc2}'?"
                    qas.append({
                        "type": "Adversarial",
                        "template": "G_shortest_path_adversarial",
                        "question": q,
                        "paraphrase": para(q),
                        "difficulty": n,
                        "range": [0, n - 1],
                        "gt": "not answerable",
                    })
                    pairs_tried += 1
                    if pairs_tried >= max_per_type:
                        break
            if pairs_tried >= max_per_type:
                break

    # -------------------------------
    # Adversarial: pooled gain-item (NEW) + no repeats within this log
    # -------------------------------
    # Collect items seen in this trajectory (inventory + gain_events keys)
    seen_items = set()
    for inv in qa_utils.inventory[:n]:
        if inv:
            for it in inv:
                if it:
                    seen_items.add(str(it))
    for it, idxs in qa_utils.gain_events.items():
        if idxs:
            seen_items.add(str(it))

    # Anchor item: sample a real seen item to get same-cluster hard negative
    anchor_item = random.choice(list(seen_items)) if seen_items else ""

    for _ in range(max_per_type):
        fake_item = pick_negative_from_pool(
            anchor=anchor_item,
            pool_type="item",
            seen_terms=list(seen_items | used_neg_items),
            pool_path="game_envs/items_locations.json",
            rng=random,
        )
        if not fake_item:
            break

        used_neg_items.add(fake_item)

        q = f"At which step did you gain '{fake_item}' for the last time?"
        qas.append({
            "type": "Adversarial",
            "template": "G_gain_item_adversarial_pool",
            "question": q,
            "paraphrase": para(q),
            "difficulty": 1,
            "range": [0, n - 1],
            "gt": "not answerable",
        })

        # diversify anchor to avoid repeatedly sampling the same neighborhood
        anchor_item = fake_item

    # -------------------------------
    # Adversarial: pooled fake-location tasks (NEW) - 4 distinct fakes (no repeats within this log)
    #   q2 uses (a,b), q1 uses (c), q3 uses (d)
    # -------------------------------
    def _norm(s: str) -> str:
        return re.sub(r"\s+", " ", (s or "").strip().lower())

    seen_locs = set([loc for loc in qa_utils.locations[:n] if loc])

    # Anchor location from trajectory to select hard negative within same cluster
    anchor_loc = random.choice(list(seen_locs)) if seen_locs else ""

    # Forbidden terms: already in log + already used as negatives in this log
    forbidden_locs = set(seen_locs) | set(used_neg_locs)
    forbidden_locs_norm = set(_norm(x) for x in forbidden_locs)

    def _pick_new_fake_loc(anchor: str) -> str:
        nonlocal forbidden_locs, forbidden_locs_norm
        for _ in range(20):
            cand = pick_negative_from_pool(
                anchor=anchor,
                pool_type="location",
                seen_terms=list(forbidden_locs),
                pool_path="game_envs/items_locations.json",
                rng=random,
            )
            if not cand:
                continue
            ck = _norm(cand)
            if ck in forbidden_locs_norm:
                continue
            # accept
            forbidden_locs.add(cand)
            forbidden_locs_norm.add(ck)
            used_neg_locs.add(cand)
            return cand
        return ""

    # Sample up to 4 unique fake locations (without replacement)
    fake_locs = []
    for _ in range(4):
        if seen_locs:
            a = random.choice(list(seen_locs))
        elif fake_locs:
            a = fake_locs[-1]
        else:
            a = anchor_loc
        x = _pick_new_fake_loc(a)
        if x:
            fake_locs.append(x)

    fake_loc_a = fake_locs[0] if len(fake_locs) > 0 else ""
    fake_loc_b = fake_locs[1] if len(fake_locs) > 1 else ""
    fake_loc_c = fake_locs[2] if len(fake_locs) > 2 else ""
    fake_loc_d = fake_locs[3] if len(fake_locs) > 3 else ""

    # Choose an action that definitely exists in the trajectory for the phrasing
    action_candidates = [a for a in qa_utils.actions[:n] if a and str(a).strip()]
    anchor_action = random.choice(action_candidates) if action_candidates else "look"

    # Pick an anchor step for the "location at step X" phrasing
    anchor_step_idx = random.randint(0, n - 1)
    anchor_step_num = step_num(anchor_step_idx)

    # (1) first leave fake location before performing the action  -> use fake_loc_c
    if fake_loc_c:
        q1 = f"At which step did you first leave '{fake_loc_c}' before performing the action '{anchor_action}'?"
        qas.append({
            "type": "Adversarial",
            "template": "G_leave_fake_location_before_action",
            "question": q1,
            "paraphrase": para(q1),
            "difficulty": n,
            "range": [0, n - 1],
            "gt": "not answerable",
        })

    # (2) closer-to-reach comparison with two fake locations -> use fake_loc_a / fake_loc_b
    if fake_loc_a and fake_loc_b and _norm(fake_loc_a) != _norm(fake_loc_b):
        q2 = (
            f"From the location at step {anchor_step_num}, which is closer in terms of fewer steps to reach, "
            f"'{fake_loc_a}' or '{fake_loc_b}'?"
        )
        qas.append({
            "type": "Adversarial",
            "template": "G_closer_two_fake_locations",
            "question": q2,
            "paraphrase": para(q2),
            "difficulty": n,
            "range": [0, n - 1],
            "gt": "not answerable",
        })

    # (3) stay length after first entering fake location -> use fake_loc_d
    if fake_loc_d:
        q3 = f"After first time entering '{fake_loc_d}', how many steps did you stay in this location?"
        qas.append({
            "type": "Adversarial",
            "template": "G_stay_len_fake_location",
            "question": q3,
            "paraphrase": para(q3),
            "difficulty": n,
            "range": [0, n - 1],
            "gt": "not answerable",
        })


    # Before final deduplication, limit the number of multi-hop (B_*) tasks per template.
    # Multi-hop templates (those beginning with 'B_') can produce many combinations.  Here
    # we randomly shuffle and select up to `max_per_type` tasks per such template.
    tasks_by_template: Dict[str, List[Dict[str, Any]]] = defaultdict(list)
    for t in qas:
        tmpl = t.get("template", "")
        tasks_by_template[tmpl].append(t)
    reduced_qas: List[Dict[str, Any]] = []
    for tmpl, ts in tasks_by_template.items():
        if tmpl.startswith("B_") and len(ts) > max_per_type:
            random.shuffle(ts)
            ts = ts[:max_per_type]
        reduced_qas.extend(ts)
    qas = reduced_qas

    # Final deduplication to remove any remaining duplicate questions
    final_qas: List[Dict[str, Any]] = []
    seen_final: set = set()
    for t in qas:
        key = (t["template"], t["question"])
        if key in seen_final:
            continue
        seen_final.add(key)
        final_qas.append(t)
    return final_qas


def main() -> None:
    ap = argparse.ArgumentParser(description="Generate Jericho QA pairs and dynamic map from logs.")
    # Provide defaults for arguments to simplify usage.  These defaults mirror
    # typical project paths but can be overridden on the command line.
    ap.add_argument(
        "--input-dir",
        default="/Users/xinzeli/Documents/mem_eval_game/text_game/logs/advent",
    )
    ap.add_argument(
        "--default-folder",
        default="gpt-5.1_history30_20251119_135936",
    )
    ap.add_argument(
        "--game",
        default="advent",
    )
    ap.add_argument(
        "--output-dir",
        default="/Users/xinzeli/Documents/mem_eval_game/text_game/generated_qa",
    )
    ap.add_argument(
        "--max-per-type",
        type=int,
        default=2,
    )

    # Difficulty hyperparameter.  When difficulty = -1 (default), questions whose
    # answer depends on a range of steps will use the entire trajectory.  When
    # difficulty > 0, range‐based questions will sample a contiguous window of
    # length ``difficulty`` over which the answer is computed. 
    ap.add_argument(
        "--difficulty",
        type=int,
        default=-1,
    )
    ap.add_argument(
        "--paraphrase",
        default=True,
    )
    args = ap.parse_args()

    # Construct input file path.  The log file is expected to follow the
    log_filename = f"{args.default_folder}_logs.jsonl"
    log_path = os.path.join(os.path.abspath(args.input_dir), log_filename)
    if not os.path.isfile(log_path):
        raise SystemExit(f"Log file not found: {log_path}")

    # Read the log
    records = load_jsonl(log_path)
    if not records:
        raise SystemExit(f"No valid records found in: {log_path}")

    # Build QA utilities and dynamic map
    qa_utils = JerichoQAUtils(records)
    dynamic_map = qa_utils.dynamic_map

    # Generate questions using a comprehensive template-driven approach
    qas = generate_questions(qa_utils, difficulty=args.difficulty, max_per_type=args.max_per_type, paraphrase=args.paraphrase)
    # Perform batch paraphrasing on the generated questions.  This post-processing
    # updates the 'paraphrase' field for a subset of questions per template.
    batch_paraphrase_qas(qas, paraphrase=args.paraphrase)

    # Assemble contexts per step
    contexts: List[Dict[str, Any]] = []
    for i, rec in enumerate(qa_utils.recs):
        step_num = qa_utils.steps[i] if i < len(qa_utils.steps) else i + 1
        action = qa_utils.actions[i] or ""
        reason = qa_utils.reasons[i] or ""
        valid_actions = qa_utils.valid_actions[i] or []
        env_fb = qa_utils.env_feedback[i] or ""
        # Use cumulative reward for context; this represents the total accumulated reward up to this step
        reward = qa_utils.cum_rewards[i] if i < len(qa_utils.cum_rewards) else qa_utils.rewards[i]
        done = qa_utils.dones[i]
        context = {
            "t": step_num,
            "action": action,
            "reason": reason,
            "valid_actions": valid_actions,
            "observation": env_fb,
            "location": qa_utils.locations[i] or "",
            "reward": reward,
            "done": done,
        }
        contexts.append(context)

    dif_tag = f"DIF_{args.difficulty if args.difficulty is not None else -1}"
    out_dir = os.path.join(
        os.path.abspath(args.output_dir), args.game, args.default_folder, dif_tag
    )
    os.makedirs(out_dir, exist_ok=True)

    dynamic_map_path = os.path.join(out_dir, "dynamic_maps.json")
    write_json(dynamic_map_path, dynamic_map)

    qa_path = os.path.join(out_dir, "qa.jsonl")
    write_jsonl(qa_path, qas)

    context_path = os.path.join(out_dir, "qa_context.json")
    write_json(context_path, contexts)

    print(json.dumps({
        "records": len(records),
        "qa_pairs": len(qas),
        "output_dir": out_dir,
        "dynamic_map": os.path.relpath(dynamic_map_path, out_dir),
        "qa_file": os.path.relpath(qa_path, out_dir),
        "context_file": os.path.relpath(context_path, out_dir),
    }, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()